### PR TITLE
Linux: Handeling multithreading and better terminal settup

### PR DESCRIPTION
**Pull request by Cube707**
_Originally posted by @qianyun210603 in https://github.com/magmax/python-readchar/issues/79#issuecomment-1179482070_

This version indeed solves issue 1 in #64 but unfortunately it doesn't fix issue 2 as per my test on my ovh server (running ubuntu). Below is my test script:

```python
import sys
sys.path.insert(0, r"/root/python-readchar-v4")
from threading import Thread
from queue import Queue
from typing import Callable, Dict
import time
import logging
import readchar

logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(module)s - %(message)s', level=logging.INFO,
)

running = False


class KeyBoardMonitor(object):

    def __init__(self, callbacks: Dict[str, Callable[[str], None]] = None, quit_symbol: str = 'q'):
        self.callbacks = callbacks if callbacks else {}
        self.quit_symbol = quit_symbol
        self.running = True
        self.queue = Queue()
        self.thread = Thread(name="keyboard monitoring", target=self._keyboard_monitor)

    def register_callback(self, order: str, callback: Callable[[str], None]) -> None:
        self.callbacks[order] = callback

    def unregister_callback(self, order):
        del self.callbacks[order]

    def start(self):
        self.thread.start()

    def stop(self):
        self.running = False

    def _keyboard_monitor(self):
        while self.running:
            ch = str(readchar.readchar())
            if ch in self.callbacks:
                self.callbacks[ch](ch)
            if ch == self.quit_symbol:
                self.running = False

def myprint(ch):
    print(ch, "entered")
    if ch == 'q':
        global running
        running = False


if __name__=="__main__":
    watchdog = KeyBoardMonitor(callbacks={'q': myprint, 'p': myprint})
    watchdog.start()
    running = True
    for _ in range(300):
        if not running:
            break
        time.sleep(1)
        logging.info(f"current_time: {time.time()}")
```
copy this into file and change the path in `sys.path.insert` to the "master" branch of local clone of your repo in r"/root/python-readchar-v4", I still see unwanted blanks (should come from the `\r` generated by `setraw` and missing linebreaks between logs:
image

In contrast, if using my version in pull request #64, I can get clean log outputs.
image

Would you please take some further look?

Thanks!

### CODE REVIEW

**Comment by Cube707** [comment]
imediate issue seems fixed under debian linux: 
image

**Comment by Cube707** [comment]
@qianyun210603

I belive I found a fix by using a custom terminal configuration. This way the `CTRL_C` will still be outputed as `0x03` and not result in termination while still fixing the problem with the random whitespace. 

Your provided script runs for me but would you please test as well?

**Comment by Cube707** [comment]
Also, I don't know what your exact plans are with your code example, but I simplefied it and used this instead:

```python
from threading import Thread
from time import time, sleep
from readchar import key, readkey


# construct an inverted code -> key-name mapping
# we need to revese the items so that aliases won't overrive the original name later on
known_keys = {v: k for k, v in reversed(vars(key).items()) if not k.startswith("__")}

def keylogger():
    while running:
        data = readkey()
        if data in known_keys:
            data = known_keys[data]
        print(f"{data}-key was pressed")


def main():
    while running:
        print(f"LOG: current time is {time()}")
        sleep(1)



running = True

if __name__ == "__main__":
    Thread(name="keyreader", target=keylogger).start()
    main()
```

(keep in mind that you will need to handle KeyboardInterupts manually and that every thread will raise a seperate KeyboardInterupt)

Depending on your neede this version allows you to use `readchar.readchar(`blocking=False)` to have a non-blocking check for a keypress. It returns `None` if no key was pressed and otherwise the key.

**Comment by Cube707** [comment]
> change the path in sys.path.insert to the "master" branch of local clone of your repo in r"/root/python-readchar-v4"

my the way, it is way easieser (and more proper) to just install the relevant version into the virtual enviroment of your project instead of messing with the system-path

**Comment by qianyun210603** [comment]
> @qianyun210603
> 
> I belive I found a fix by using a custom terminal configuration. This way the `CTRL_C` will still be outputed as `0x03` and not result in termination while still fixing the problem with the random whitespace.
> 
> Your provided script runs for me but would you please test as well?

Thanks a lot Cube707! Tested and confirms your fix in branch fix-multithreading solves the problem under my server environment.

**Comment by qianyun210603** [comment]
> Also, I don't know what your exact plans are with your code example, but I simplefied it and used this instead:
> 
> ```python
> from threading import Thread
> from time import time, sleep
> from readchar import key, readkey
> 
> 
> # construct an inverted code -> key-name mapping
> # we need to revese the items so that aliases won't overrive the original name later on
> known_keys = {v: k for k, v in reversed(vars(key).items()) if not k.startswith("__")}
> 
> def keylogger():
>     while running:
>         data = readkey()
>         if data in known_keys:
>             data = known_keys[data]
>         print(f"{data}-key was pressed")
> 
> 
> def main():
>     while running:
>         print(f"LOG: current time is {time()}")
>         sleep(1)
> 
> 
> 
> running = True
> 
> if __name__ == "__main__":
>     Thread(name="keyreader", target=keylogger).start()
>     main()
> ```
> 
> (keep in mind that you will need to handle KeyboardInterupts manually and that every thread will raise a seperate KeyboardInterupt)
> 
> Depending on your needs this version allows you to use `readchar.readchar(blocking=False)` to have a non-blocking check for a keypress. It returns `None` if no key was pressed and otherwise the key.

For my plan, basically for the pull request I initialized is just to fix the random spaces generated by `tty.setraw`, for which purpose I believe your simplified one should serve well for testing.
My original code snippet might be overcomplicated for just testing the additional spaces between logs, because it is extracted from one of my trading bot project, in which the `KeyBoardMonitor` serves to provide some interactive so that I can send simple instructions during the bot is running (through the callback functions to set the flags/do operations in main classes in trading bot). 
I've been searching for solutions of this kind "non-blocking interactive commandline interface" (may not be the right terminology but should express the meaning) but unfortunately no satisfactory solution was found. This readchar package is the closest one which provides me some  ability to interact with my bot when it's running

> Depending on your needs this version allows you to use `readchar.readchar(blocking=False)` to have a non-blocking check for a keypress. It returns `None` if no key was pressed and otherwise the key.

If I understand correctly, does this mean I don't need to explicitly setup a separate thread for readchar to monitor keyboard events when the main thread is occupied by the bot?

**Comment by Cube707** [comment]
> If I understand correctly, does this mean I don't need to explicitly setup a separate thread for readchar to monitor keyboard events when the main thread is occupied by the bot?

Yes, this feature is intended for exactly that kind of scenario where you write your own loop and check back with readchar if a key was pressed every so often.

However this feature is new and not tested very much. It would be great to get some feedback on it.

Some problems that might come with it:

When checking readchar relatively rarely, the keypresses might have some other side effects before being consumed by readchar. 

`KeyboardInterupt` behaviour might be hard to define as its not guaranteed that readchar is running when `CTRL+C` is pressed.

Behaviour may differ between windows and Linux systems. Theoreticaly it should be identical, but also not fully tested

**Comment by Cube707** [comment]
here is a quick example:

```python
from time import time
from readchar import key, readchar


last = time()

while True:
    if time()-last > 1.0:
        last = time()
        print("LOG: 1 second passed")

    k = readchar(blocking=False)
    if k == key.CTRL_C:
        raise KeyboardInterrupt
    if k == "p":
        print("got p command")
```

this works as expected in my short tests on both windows and linux. But if you remove the `CTRL+C` check only the linux version will stop responding to the shutdown order. The windows version will still break on `CTRL+C` and report a random line of code in the traceback.

**Comment by Cube707** [comment]
Sidenote: I would still recomend running the bot-operations on a seperate thread, but in my opinion it would make sens to concentrate logging and input gathering into a single thread handeling all unser interaction.

**Comment by qianyun210603** [comment]
Thanks a lot for the suggestions. looking forward to see the release of v4!

**Pull request closed without merging**
